// Code generated by hertz generator.

package main

import (
	"fmt"
	"io"
	"jx-hook/biz/config"
	"os"

	"github.com/cloudwego/hertz/pkg/app/middlewares/server/basic_auth"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/hertz-contrib/logger/accesslog"
)

var serverConfig config.ServerConfig

func init() {
	serverConfig = config.ConfigInstance
}

func logFile() *os.File {
	f, err := os.OpenFile(serverConfig.LogConfig.File, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		fmt.Println("Failed to access log file", err)
	}
	return f
}

func main() {
	h := server.Default(server.WithHostPorts(serverConfig.HostPort))

	hlog.DefaultLogger().SetOutput(io.MultiWriter(logFile(), os.Stdout))
	hlog.DefaultLogger().SetLevel(hlog.Level(serverConfig.LogConfig.Level))

	hlog.Info("Init service and logger with host ", serverConfig.HostPort)

	// BASIC AUTH
	h.Use(basic_auth.BasicAuth(serverConfig.BasicAuth))

	// ACCESS LOG
	h.Use(accesslog.New(accesslog.WithFormat(serverConfig.LogConfig.AccessLogFormat)))
	register(h)

	h.Spin()
}
